import { test, expect } from "@playwright/test"

test("lançamento do FinUp persiste sem alterar o extrato do Banco TRI", async ({ page }) => {
  await page.goto("/dashboard")
  await expect(page.getByRole("heading", { name: "Olá, Junior Lummertz" })).toBeVisible()
  await expect(page.getByText("Supermercado")).toBeVisible()

  await page.getByRole("link", { name: "FinUp" }).click()
  await expect(page.getByRole("heading", { name: "Visão financeira" })).toBeVisible()
  await page.getByLabel("Descrição").fill("Despesa de teste")
  await page.getByLabel("Valor (R$)").fill("12.50")
  await page.getByRole("button", { name: "Adicionar lançamento" }).click()
  await expect(page.getByText("Lançamento adicionado ao FinUp.")).toBeVisible()
  await expect(page.getByText("Despesa de teste")).toBeVisible()

  await page.reload()
  await expect(page.getByText("Despesa de teste")).toBeVisible()
  await page.getByRole("button", { name: "Editar Despesa de teste" }).click()
  await page.getByLabel("Descrição").fill("Material da oficina")
  await page.getByLabel("Valor (R$)").fill("19,90")
  await page.getByRole("button", { name: "Salvar alterações" }).click()
  await expect(page.getByText("Lançamento atualizado no FinUp.")).toBeVisible()
  await page.reload()
  await expect(page.getByText("Material da oficina")).toBeVisible()
  await page.getByRole("button", { name: "Excluir Material da oficina" }).click()
  await page.getByRole("button", { name: "Cancelar", exact: true }).click()
  await expect(page.getByText("Material da oficina")).toBeVisible()
  await page.getByRole("button", { name: "Excluir Material da oficina" }).click()
  await page.getByRole("button", { name: "Confirmar exclusão" }).click()
  await expect(page.getByText("Material da oficina")).toHaveCount(0)

  await page.getByRole("link", { name: "Início" }).click()
  await expect(page.getByRole("heading", { name: "Olá, Junior Lummertz" })).toBeVisible()
  await expect(page.getByText("Supermercado")).toBeVisible()
  await expect(page.getByText("Despesa de teste")).toHaveCount(0)
  await page.getByLabel("Buscar movimentação").fill("farmacia")
  await expect(page.getByText("Farmácia")).toBeVisible()
  await expect(page.getByText("Supermercado")).toHaveCount(0)
  await page.getByLabel("Tipo de movimentação").selectOption("credit")
  await expect(page.getByText("Nenhuma movimentação corresponde aos filtros.")).toBeVisible()
})
