import { test, expect } from "@playwright/test"

test("lançamento do FinUp persiste sem alterar o extrato do Banco TRI", async ({ page }) => {
  await page.goto("/dashboard")
  await expect(page).toHaveURL(/\/$/)
  await page.getByRole("button", { name: "Entrar na conta" }).click()
  await expect(page.getByRole("heading", { name: "Olá, Junior Lummertz" })).toBeVisible()
  await expect(page.getByText("Supermercado")).toBeVisible()

  await page.getByRole("link", { name: "FinUp" }).click()
  await expect(page.getByRole("heading", { name: "Visão financeira" })).toBeVisible()
  await page.getByRole("combobox", { name: /^Tipo / }).click()
  await page.getByRole("option", { name: "Receita" }).click()
  await expect(page.getByRole("combobox", { name: /^Tipo / })).toContainText("Receita")
  await page.getByRole("combobox", { name: /^Tipo / }).click()
  await page.getByRole("option", { name: "Despesa" }).click()
  const category = page.getByRole("combobox", { name: /^Categoria / })
  await category.focus()
  await category.press("ArrowDown")
  await page.getByRole("option", { name: "Alimentação" }).press("ArrowDown")
  await page.getByRole("option", { name: "Moradia" }).press("Enter")
  await expect(category).toContainText("Moradia")
  await page.getByRole("button", { name: /^Data / }).click()
  await page.getByRole("button", { name: "Mês anterior" }).click()
  await page.getByRole("button", { name: "Próximo mês" }).click()
  await page.getByRole("dialog", { name: "Escolher data" }).locator(".calendar-day[aria-pressed='true']").press("ArrowRight")
  await page.getByRole("dialog", { name: "Escolher data" }).locator(".calendar-day:focus").press("Enter")
  await page.getByRole("button", { name: /^Data / }).click()
  await page.getByRole("button", { name: "Ir para hoje" }).click()
  await page.getByLabel("Descrição").fill("Despesa de teste")
  await page.getByLabel("Valor (R$)").fill("12.50")
  await page.getByRole("button", { name: "Adicionar lançamento" }).click()
  await expect(page.getByText("Lançamento adicionado ao FinUp.")).toBeVisible()
  await expect(page.getByText("Despesa de teste")).toBeVisible()

  await page.reload()
  await expect(page.getByText("Despesa de teste")).toBeVisible()
  await page.getByRole("button", { name: "Editar Despesa de teste" }).click()
  await page.getByLabel("Descrição").fill("Material da oficina")
  await page.getByLabel("Valor (R$)").fill("19,90")
  await page.getByRole("button", { name: "Salvar alterações" }).click()
  await expect(page.getByText("Lançamento atualizado no FinUp.")).toBeVisible()
  await page.reload()
  await expect(page.getByText("Material da oficina")).toBeVisible()
  await page.getByRole("button", { name: "Excluir Material da oficina" }).click()
  await page.getByRole("button", { name: "Cancelar", exact: true }).click()
  await expect(page.getByText("Material da oficina")).toBeVisible()
  await page.getByRole("button", { name: "Excluir Material da oficina" }).click()
  await page.getByRole("button", { name: "Confirmar exclusão" }).click()
  await expect(page.getByText("Material da oficina")).toHaveCount(0)

  await page.getByRole("link", { name: "Visão geral" }).click()
  await expect(page.getByRole("heading", { name: "Olá, Junior Lummertz" })).toBeVisible()
  await expect(page.getByText("Supermercado")).toBeVisible()
  await expect(page.getByText("Despesa de teste")).toHaveCount(0)
  await page.getByLabel("Buscar movimentação").fill("farmacia")
  await expect(page.getByText("Farmácia")).toBeVisible()
  await expect(page.getByText("Supermercado")).toHaveCount(0)
  await page.getByRole("combobox", { name: /^Tipo de movimentação/ }).click()
  await page.getByRole("option", { name: "Entradas" }).click()
  await expect(page.getByText("Nenhuma movimentação corresponde aos filtros.")).toBeVisible()
  await page.getByRole("button", { name: "Sair da demonstração" }).click()
  await expect(page.getByRole("button", { name: "Entrar na conta" })).toBeVisible()
  await page.goto("/finup")
  await expect(page).toHaveURL(/\/$/)
})
